### ISSUE TITLE
Unit tests failing with material-table/core 4.1.0.

### ISSUE THREAD

**Issue by debajit-saha** [material-table-core/core#300]
-  I am using Jest and Enzyme to write unit test cases for react app. In those unit test files, where we have import statements for Material Table, the complete test suit is failing. The error message provided by Jest is below:
_Test suite failed to run
Jest encountered an unexpected token
This usually means that you are trying to import a file that Jest cannot parse, e.g. it's not plain JavaScript._

- I checked the next recent version 4..0.0, the issue persists there too. But with version 3.2.5, all tests were passing. See the below screenshot for more detail.

**Screenshots**
(Image 1)
![unit_test_fail2](https://user-images.githubusercontent.com/22059269/128303163-585eecb0-8a4b-4aaa-b0ac-14c12bb2025f.png)

(Image 2)
![image](https://user-images.githubusercontent.com/22059269/128305345-a67cc6da-c49b-44b0-b9af-b952233cfbcb.png)

As the error message suggests possible solutions for the failing tests. I applied 2nd point from the "what you can do" section (Image 2) and added "material-core/table" in the transformIgnorePatterns property in the package.json file. The tests are passing with this change. 
So, why do we need to add it to transformIgnorePatterns for tests to work?

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: NA
- React version:  16.13.1
- Material-Table/Core - 4.0.1
- Jest: 26.6.3

**Comment by matthewoestreich** [comment]
We changed how we bundle this library. That's why that is needed, I will update docs.

**Comment by debajit-saha** [comment]
> We changed how we bundle this library. That's why that is needed, I will update docs.

Thanks, @oze4 for the information.

**Comment by cwpinto23** [comment]
Hi @debajit-saha , what did you add to your transformIgnorePatterns? I can't seem to get mine to work:
```
   "transformIgnorePatterns": [
      "node_modules/(?!@material-table/core)"
    ],
```

**Comment by debajit-saha** [comment]
This is what I have in transformIgnorePatterns. Try this.

  "transformIgnorePatterns": [
   "node_modules/(?!(jest-)?@material-table/core)"
  ]

**Comment by cwpinto23** [comment]
Still breaking for me unfortunately. Works if I drop back to 3.2.5.

```
node_modules\@material-table\core\dist\index.js:2
    import "./utils/polyfill";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import { basicGet } from '../../api/axiosGet'
      3 | import { makeStyles } from '@material-ui/core/styles';
    > 4 | import MaterialTable from '@material-table/core';
        | ^
      5 | import CircularProgress from '@material-ui/core/CircularProgress';
      6 |
      7 |

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (components/table-components/generic-table.js:4:1)
```

And here's my jest settings in my package.json
```
  "jest": {
    "setupFiles": [
      "<rootDir>/__mocks__/windowMock.js",
      "<rootDir>/__mocks__/canvasMock.js",
      "<rootDir>/__mocks__/barGraphMock.js"
    ],
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!(jest-)?@material-table/core)"
    ],

    "transform": {
      "^.+\\.[t|j]sx?$": "babel-jest",
      "\\.svg$": "./__setup__/svgTransform.js"
    },
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js"
    }
  },
```

I'm running Jest with `    jest --env=jsdom`

**Comment by matthewoestreich** [comment]
@cwpinto23 we changed our transpiler in order to cut the library size nearly in half. That is when this issue started. 

I just added `"type": "module"` to our package.json file and changed the build script to use import statements (that was preventing me from using `type: module` to begin with)..

Would you mind updating to version `4.2.2` and giving this another try? It should fix the Jest error (since now it is officially a module package).

Sorry about that.

**Comment by matthewoestreich** [comment]
@debajit-saha see updates [above](https://github.com/material-table-core/core/issues/300#issuecomment-894493966)

**Comment by matthewoestreich** [comment]
# FYI

### You should no longer need the transform in your Jest config in `>= v4.2.2`

**Comment by cwpinto23** [comment]
@oze4 , still getting the same error I posted above. I tried it with and without the transformers.
I'm on Webpack 5 btw

**Comment by matthewoestreich** [comment]
I wonder if this line may be part of the issue.. `"^.+\\.[t|j]sx?$": "babel-jest",` (it doesn't pick up on just `.js` files).

Can you add the following line to your transforms just to test this theory?

```
    "transform": {
      "^.+\\.[t|j]sx?$": "babel-jest",
      "\\.js$": "babel-jest",       // <-- this line
      "\\.svg$": "./__setup__/svgTransform.js"
    },
```
For example, this is our Jest config:

https://github.com/material-table-core/core/blob/ff12774312423b57cc1c93ddc1aa261d28da90cf/jest.config.js#L188-L190

@cwpinto23

**Comment by oze4** [comment]
Also, are you ignoring `node_modules` by any chance? If not, would you mind adding that as well?

From our Jest config:

https://github.com/material-table-core/core/blob/ff12774312423b57cc1c93ddc1aa261d28da90cf/jest.config.js#L170

**Comment by matthewoestreich** [comment]
Also, it may be silly but could you try deleting node_modules and running `npm install` again? Just to make sure you have the new package.json file with `type: module`?

**Comment by matthewoestreich** [comment]
If I recall correctly we had to do the same thing because one of our deps was using modules (same situation you're in).

Jest doesn't understand es6 by default, so you have to run it thru babel first.

https://stackoverflow.com/a/64223627/10431732

In fact, the biggest reason our library size is half of what it was is because we no longer need that injected babel polyfill code that makes it work (and also bloats prod builds).

Since it's a React project we reasoned you're already using es6 features, which is why this issue only occurs with Jest. And not while running a dev server, etc...Jest doesn't use es6 by default.

**Comment by cwpinto23** [comment]
Alright, so I:

- deleted and reinstalled node modules
- created a babel.config.js that I set to `  module.exports = {presets: ['@babel/preset-env']} `
-  updated my transform to 
``` 
"transform": {
      "^.+\\.(js|jsx)$": "babel-jest",
      "\\.svg$": "./__setup__/svgTransform.js"
    },
```

I also tried specifically pointing to the babel.config.js in my transform
```
 "transform": {
      "\\.js$": ["babel-jest", { "configFile": "./babel.config.js" }],
      "^.+\\.[t|j]sx?$": "babel-jest",
      "\\.svg$": "./__setup__/svgTransform.js"
    },
```


Confirmed I have the version of package.json specified as a module
![image](https://user-images.githubusercontent.com/85768119/128573451-fabe99de-80dc-4618-9a34-ac595a69a3b2.png)

Here's the full error (slightly different from before), seems to be focusing on MTablePagination:


```
node_modules\@material-table\core\dist\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){var a=Object.assign;import"./utils/pol
yfill";import t from"react";import{defaultProps as l}from"./defaults";import{propTypes as i}from"./prop-types";import o from"./mate
rial-table";import{withStyles as r}from"@material-ui/core";o.defaultProps=l,o.propTypes=i;const p=e=>({paginationRoot:{width:"100%"
},paginationToolbar:{padding:0,width:"100%"},paginationCaption:{display:"none"},paginationSelectRoot:{margin:0}});export default r(
p,{withTheme:!0})(e=>t.createElement(o,a(a({},e),{ref:e.tableRef})));export{MTableAction,MTableActions,MTableBody,MTableBodyRow,MTa
bleCell,MTableEditCell,MTableEditField,MTableEditRow,MTableFilterRow,MTableGroupRow,MTableGroupbar,MTableHeader,MTablePagination,MT
ableSteppedPagination,MTableToolbar}from"./components";
                                                                                                                 ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import { basicGet } from '../../api/axiosGet'
      3 | import { makeStyles } from '@material-ui/core/styles';
    > 4 | import MaterialTable from '@material-table/core';
        | ^
      5 | import CircularProgress from '@material-ui/core/CircularProgress';
      6 |
      7 |

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (components/table-components/generic-table.js:4:1)

```

Worst case scenario, I can continue to use 3.2.5

**Comment by oze4** [comment]
Can you add the `"type": "module"` to your package.json file?

**Comment by matthewoestreich** [comment]
Just to make sure.. you did run `npm i -D @babel/preset-env` correct? If you did, can you add the `"type": "module"` to your package.json file? I don't understand why it doesn't work for you.. There's something I'm missing..

**Comment by cwpinto23** [comment]
Yes to the preset-env, here's the start of my devDependencies:
```
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.15.0",
    "@babel/preset-react": "^7.14.5",
```

I tried adding the "type": "module" to my package.json as well, but same error as before

**Comment by matthewoestreich** [comment]
Is your project public? If not I'd like to create a POC repo that mirrors your setup as closely as possible. It doesn't make sense why it's not working for you :(

**Comment by cwpinto23** [comment]
Ah, sorry, private repo for my company. I'll try and setup a public repo on my personal that's a bare minimum repeat of the setup that triggers the error

**Comment by matthewoestreich** [comment]
Are you using a home grown webpack config or are you using create-react-app?

Also, are you using React 16.x?

I can get something started - I don't mind helping :)

**Comment by cwpinto23** [comment]
All good, I got one up here: https://github.com/cwpinto23/test-material-table
And yes, home-grown webpack config, and     "react": "^16.12.0".

I left a few additional packages in there, because I wasn't sure if they were related (plotly, core-js2). Probably can dump those to speed up the  package install time.

**Comment by matthewoestreich** [comment]
It def seems like something specific to that project. Just have to find it lol. It doesn't make sense how we don't even get that error when testing. It seems like it works for some but not for others?

I'm going to create a fresh react project with homegrown webpack, etc.. to see if I get the error there as well.

I tried changing so many things but still got the error in your demo. I don't understand why.

**Comment by matthewoestreich** [comment]
cc @Domino987 any ideas?

**Comment by Domino987** [comment]
Yes its the project but I am not sure why yet. I am looking into it as well.

**Comment by matthewoestreich** [comment]
@cwpinto23 @debajit-saha we went ahead and changed our build steps back to how it was before (a little larger library size, but at least these edge case bugs will be resolved).

v4.3.0 should work for you like normal. Please let me know if you have any questions.

**Comment by debajit-saha** [comment]
Yep, verified with v4.3.0. All tests are passing w/o adding to transformIgnorePatterns. Thanks, @oze4

**Comment by matthewoestreich** [comment]
Going to close this one out for now.

**Comment by cwpinto23** [comment]
@oze4 , just wanted to say 4.3.0 is working on my end. Thanks for all the help!
