### ISSUE TITLE
 Failed to parse source map of react-double-scrollbar 

### ISSUE THREAD

**Issue by TCM5** [material-table-core/core#467]
**Describe the bug**
This is not a material-table-core problem itself, but a rather from the dependecy react-double-scrollbar. This was already reported in rds repository [(https://github.com/umchee/react-double-scrollbar/issues/9)](https://github.com/umchee/react-double-scrollbar/issues/9) , and seems to be introduced on the release that material-table-core is using. 

The project react-double-scrollbar seems to be not very active, so maybe a version downgrade of this dependecy should be performed.

**To Reproduce**
Just install the latest version of material-table-core and start application. 

**Additional context**
A workaround is to disable the source map generation or add a resolution in case of using package.json.

**Comment by Domino987** [comment]
Well it looks like even earlier versions have the same problem, so downgrading does not fix this.
And since its just a warning, not sure if this is too urgent.

**Comment by scrozier** [comment]
I'm seeing the same thing. Agreed that it's not urgent, but it does really clutter up my `npm start` window, making it a bit harder to find genuine issues. I'll have a look to see if there's a reasonable fix.

**Comment by sairam0903** [comment]
As a work around to disable source maps, please refer to https://github.com/mswjs/msw/issues/1030#issuecomment-1004245791

**Comment by strawji02** [comment]
> As a work around to disable source maps, please refer to [mswjs/msw#1030 (comment)](https://github.com/mswjs/msw/issues/1030#issuecomment-1004245791)

Disabling the sourcemap makes the typescript server very slow. I want to see the beautiful npm start window.

**Comment by oskarlh** [comment]
Can this be reopened? It's still an issue. The owner of react-double-scrollbar has been inactive on GitHub for over 5 years - react-double-scrollbar will not be fixed

**Comment by Domino987** [comment]
I am open for suggestions on how to fix this.

**Comment by oskarlh** [comment]
Forking or replacing the library

**Comment by Domino987** [comment]
Go ahead ;)

**Comment by donavan-tangible** [comment]
Consider to use this fork until the fix is merged

package.json:
...
"dependencies": {
"react-double-scrollbar": "https://github.com/IniterWorker/react-double-scrollbar.git",
}

**Comment by oskarlh** [comment]
@donovan-tangible Nice. Should you add `#package-map-missing-issue` after `.git` to get the right branch?

**Comment by donavan-tangible** [comment]
Finally, in my package.json file, I make it work like this:

package.json:
```
{
...
"dependencies": {
...
},
  "resolutions": {
    "react-double-scrollbar": "https://github.com/IniterWorker/react-double-scrollbar.git"
  },
}
```

**Comment by imnasnainaec** [comment]
@donavan-tangible's solution is for `yarn`.

The `npm` solution uses `overrides`:
```
  "overrides": {
    "react-double-scrollbar": "IniterWorker/react-double-scrollbar"
  },
```

See https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides, https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls.

**Comment by imnasnainaec** [comment]
@donavan-tangible Thank you for forking this repo to help solve this issue! The above addition to my `package.json` does successfully pull from your fork, but doesn't resolve the issue because your `master` branch is identical to umchee's. When I use `"IniterWorker/react-double-scrollbar#a59d281"` to pull from your `package-map-missing-issue` branch, my compile fails to resolve:

```
Failed to compile.

Module not found: Error: Can't resolve 'react-double-scrollbar' in '[...]/node_modules/@material-table/core/dist/components/MTableScrollbar'
ERROR in ./node_modules/@material-table/core/dist/components/MTableScrollbar/index.js 10:51-84
Module not found: Error: Can't resolve 'react-double-scrollbar' in '[...]/node_modules/@material-table/core/dist/components/MTableScrollbar'

webpack compiled with 1 error
```

In this case, my `node_modules/react-double-column` is just a copy of the branch without the `dist` or its contents.

**Comment by donavan-tangible** [comment]
@imnasnainaec 
Can you try with this in your package.json:
...
  "resolutions": {
    "react-double-scrollbar": "https://github.com/IniterWorker/react-double-scrollbar.git"
  },
...

**Comment by oskarlh** [comment]
@donavan-tangible That doesn't work. We need `#package-map-missing-issue` after `.git` because your changes are in the "package-map-missing-issue" branch

**Comment by donavan-tangible** [comment]
@oskarlh 
From our side it works really well with yarn. 
I didn't test with npm... 
Maybe you will need to propose solution with npm.

**Comment by Domino987** [comment]
Yes both should work for this change to be implemented 😉 that is for looking into this though

**Comment by imnasnainaec** [comment]
The `DoubleScrollbar` isn't even necessary. It's currently being used here for its style, even though `react-double-scrollbar` doesn't have any custom styling. Its contribution is entirely about position/location. Here's a pr to dump the troublesome package: https://github.com/material-table-core/core/pull/804

**Comment by amir0ff** [comment]
> @donavan-tangible Thank you for forking this repo to help solve this issue! The above addition to my `package.json` does successfully pull from your fork, but doesn't resolve the issue because your `master` branch is identical to umchee's. When I use `"IniterWorker/react-double-scrollbar#a59d281"` to pull from your `package-map-missing-issue` branch, my compile fails to resolve:
> 
> ```
> Failed to compile.
> 
> Module not found: Error: Can't resolve 'react-double-scrollbar' in '[...]/node_modules/@material-table/core/dist/components/MTableScrollbar'
> ERROR in ./node_modules/@material-table/core/dist/components/MTableScrollbar/index.js 10:51-84
> Module not found: Error: Can't resolve 'react-double-scrollbar' in '[...]/node_modules/@material-table/core/dist/components/MTableScrollbar'
> 
> webpack compiled with 1 error
> ```
> 
> In this case, my `node_modules/react-double-column` is just a copy of the branch without the `dist` or its contents.

Hey there 👋🏼 😄 

what is the solution until #804 is merged?

were you able to solve the issue?

**Comment by imnasnainaec** [comment]
@amir0ff I never managed a work-around; #804 is my first solution.

**Comment by amir0ff** [comment]
> @amir0ff I never managed a work-around; #804 is my first solution.

Thanks for the quick reply!

I gave up for now and committed my repo with that webpack compile warning 😄 

Things are still working for now 👍🏼

**Comment by Domino987** [comment]
I'll merge this tomorrow.
